### ISSUE TITLE
JamesLab.ps1 is empty.

### ISSUE THREAD

**Issue by QuentinEscott** [psjamesp/MOL-Scripting#1]
James,

The file JamesLab.ps1 is empty. This one https://github.com/psjamesp/MOL-Scripting/blob/main/JamesLab.ps1

Regards,
Quentin Escott

**Comment by psjamesp** [comment]
Thanks for letting me know. I’ll get it updated.

Thanks,
James

On Jan 10, 2024, at 2:11 AM, QuentinEscott ***@***.***> wrote:

﻿

James,

The file JamesLab.ps1 is empty. This one https://github.com/psjamesp/MOL-Scripting/blob/main/JamesLab.ps1

Regards,
Quentin Escott

**Comment by psjamesp** [comment]
I'm still working on this. My computer crashed a while back and I'm not on a mac. Which automated lab doesn't work on. I hope to have one for you soon.

**Comment by hk-sain** [comment]
Any updates on getting the file updated?
Can we restore a previous version from GitHub backup

**Comment by psjamesp** [comment]
I have updated the lab definition file here https://github.com/psjamesp/MOL-Scripting/blob/main/JamesLab.ps1

**Comment by psjamesp** [comment]
closed
